// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

`include "prim_assert.sv"
/**
 * OTBN Bignum MAC which supports vectorized (montgomery) multiplication
 * This module implements the 64b multiply and 256b accumulate functionality as well as supports
 * vectorized multiplication of 32b elements and vectorized 32b Montgomery multiplication.
 * The 32b vector elements are taken from 256b WDRs and vectors are processed in 64b chunks.
 * The multiplications are performed using a vectorized multiplier which sums the partial products
 * of a 64b multiplication depending on the selected element width (see otbn_vec_multiplier.sv).
 * Regular MAC functionality is performed combinatorially. The vectorized multiplication requires
 * 4 cycles (4x 64b) and the Montgomery multiplication requires 12 cycles (see below).
 *
 * The ACC register is used to store the intermediate results of the vectorized multiplications.
 * The vectorized multiplication operates elementwise or in a "lane mode" where all elements of one
 * vector are multiplied with one element of the other vector.
 *
 * Montgomery implementation details:
 * The Montgomery algorithm efficiently computes a multiplication and reduces it by a modulus.
 * This module implements the unsigned version of Montgomery.
 * The inputs must be pre-transformed into Montgomery space: a_ = a * 2^d mod q.
 *
 * Algorithm inputs:
 * - a, b: Operands in [0, q[ in Montgomery space
 * - d:    Bitwith of operands
 * - q:    Modulus in ]0, 2^d]
 * - mu:   Montgomery constant, precomputed, mu = (-q)^(-1) mod 2^d
 *
 * Outputs:
 * - r = a*b * 2^(-d) mod q and r in [0,q[
 *
 * Algorithm (where []_d are the lower d bits, []^d are the higher d bits):
 *   c = a * b
 *   r = [c + [[c]_d * mu]_d * q]^d
 *   if r >= q then                      <- not implemented in this HW
 *       return r - q
 *   return r
 *
 * To save area the Montgomery algorithm is split over 3 cycles to reuse the multiplier.
 * This requires two new registers for temporary values named "TMP" and "C". In addition, the final
 * conditional subtraction (if r >= q) is also not implemented in hardware as it can be performed
 * with a bn.addvm instruction. This optimizes area and timing. When processing a vector chunk, the
 * following cycles are executed:
 *   Cycle 1:  Reg(TMP) = [a*b]_d,     Reg(C) = a*b
 *   Cycle 2:  Reg(TMP) = [TMP*mu]_d,  Reg(C) = a*b
 *   Cycle 3:  Output   = c + (TMP)*q mod q = [c + (TMP)*q]^d
 *
 * The required constants q and mu are expected to be in the MOD WSR at following locations:
 * q  @ [31:0]
 * mu @ [63:32]
 *
 * The multiplier and adders are vectorized allowing us to compute two 32b values at
 * once. Thus for processing the 256b vector (with 8 32b elements) we require
 * 4*3 = 12 cycles. All control signals are generated by a internal state machine. The result of
 * each 64b chunk is stored in the bignum MAC module's register ACC before the final result is
 * written back into the destination WDR.
 *
 * All three internal registers (ACC, TMP and C) can be cleared with either a secure wipe or by
 * overwriting it via the ispr interface of the ACC register. In both cases all three registers
 * are set to the same value.
 */
module otbn_mac_bignum
  import otbn_pkg::*;
(
  input logic clk_i,
  input logic rst_ni,

  input mac_bignum_operation_t operation_i,
  input logic                  mac_en_i,
  input logic                  mac_commit_i,

  output logic [WLEN-1:0] operation_result_o,
  output logic            operation_valid_o,
  output flags_t          operation_flags_o,
  output flags_t          operation_flags_en_o,
  output logic            operation_intg_violation_err_o,

  input  mac_bignum_predec_t predec_i,
  output logic               predec_error_o,

  input  logic [WLEN-1:0] urnd_data_i,
  input  logic            sec_wipe_acc_urnd_i,
  input  logic            sec_wipe_tmp_urnd_i,
  input  logic            sec_wipe_c_urnd_i,
  input  logic            sec_wipe_running_i,
  output logic            sec_wipe_err_o,

  output logic [ExtWLEN-1:0] ispr_acc_intg_o,
  input  logic [ExtWLEN-1:0] ispr_acc_wr_data_intg_i,
  input  logic               ispr_acc_wr_en_i,

  input  logic [ExtWLEN-1:0] ispr_mod_intg_i
);
  localparam int HWLEN    = WLEN / 2;
  localparam int ExtHWLEN = HWLEN * 39 / 32;
  localparam int BaseWordsPerHWLEN = HWLEN / 32;

  localparam int QWLEN    = WLEN / 4;
  localparam int ExtQWLEN = QWLEN * 39 / 32;
  localparam int BaseWordsPerQWLEN = QWLEN / 32;

  typedef enum logic [1:0] {
    MulOpB,
    MulOpMu,
    MulOpq
  } mul_op_b_sel_e;

  // Encoding generated with:
  // $ ./util/design/sparse-fsm-encode.py -d 3 -m 16 -n 8 \
  //     -s 5799399942 --language=sv
  //
  // Hamming distance histogram:
  //
  //  0: --
  //  1: --
  //  2: --
  //  3: ||||||||||||||||| (30.83%)
  //  4: |||||||||||||||||||| (35.83%)
  //  5: ||||||||| (17.50%)
  //  6: |||||| (10.83%)
  //  7: || (5.00%)
  //  8: --
  //
  // Minimum Hamming distance: 3
  // Maximum Hamming distance: 7
  // Minimum Hamming weight: 2
  // Maximum Hamming weight: 6
  //
  localparam int StateMacWidth = 8;
  typedef enum logic [StateMacWidth-1:0] {
    MacRegular       = 8'b00100011, // includes: MacStartQW0, MacStartModQW0C0
    MacQW1           = 8'b01010000,
    MacQW2           = 8'b10010100,
    MacDoneQW        = 8'b10011001,
    MacModQW0C1      = 8'b11001110,
    MacModQW0C2      = 8'b01101010,
    MacModQW1C0      = 8'b10101100,
    MacModQW1C1      = 8'b00001101,
    MacModQW1C2      = 8'b11101001,
    MacModQW2C0      = 8'b01100100,
    MacModQW2C1      = 8'b11110110,
    MacModQW2C2      = 8'b00010111,
    MacModQW3C0      = 8'b01111101,
    MacModQW3C1      = 8'b11000101,
    MacDoneModQW3C2  = 8'b10111010,
    MacError         = 8'b01011011
  } mac_state_e;

  mac_state_e mac_state_d, mac_state_q;

  //////////////////
  // ACC Register //
  //////////////////
  logic                          acc_wr_en;
  logic [ExtWLEN-1:0]            acc_intg_d;
  logic [ExtWLEN-1:0]            acc_intg_q;
  logic [ExtWLEN-1:0]            acc_intg_calc;
  logic [WLEN-1:0]               acc_no_intg_d;
  logic [WLEN-1:0]               acc_no_intg_q;
  logic [2*BaseWordsPerWLEN-1:0] acc_intg_err;
  for (genvar i_word = 0; i_word < BaseWordsPerWLEN; i_word++) begin : g_acc_words
    prim_secded_inv_39_32_enc i_secded_enc (
      .data_i(acc_no_intg_d[i_word*32+:32]),
      .data_o(acc_intg_calc[i_word*39+:39])
    );
    prim_secded_inv_39_32_dec i_secded_dec (
      .data_i    (acc_intg_q[i_word*39+:39]),
      .data_o    (/* unused because we abort on any integrity error */),
      .syndrome_o(/* unused */),
      .err_o     (acc_intg_err[i_word*2+:2])
    );
    assign acc_no_intg_q[i_word*32+:32] = acc_intg_q[i_word*39+:32];
  end

  always_ff @(posedge clk_i) begin
    if (acc_wr_en) begin
      acc_intg_q <= acc_intg_d;
    end
  end

  ////////////////
  // Register C //
  ////////////////
  logic                           c_wr_en;
  logic [ExtHWLEN-1:0]            c_intg_d;
  logic [ExtHWLEN-1:0]            c_intg_q;
  logic [HWLEN-1:0]               c_no_intg_d;
  logic [HWLEN-1:0]               c_no_intg_q;
  logic [2*BaseWordsPerHWLEN-1:0] c_intg_err;

  for (genvar i_word = 0; i_word < BaseWordsPerHWLEN; i_word++) begin : g_c_words
    prim_secded_inv_39_32_enc i_c_secded_enc (
      .data_i(c_no_intg_d[i_word*32+:32]),
      .data_o(c_intg_d[i_word*39+:39])
    );
    prim_secded_inv_39_32_dec i_c_secded_dec (
      .data_i    (c_intg_q[i_word*39+:39]),
      .data_o    (/* unused because we abort on any integrity error */),
      .syndrome_o(/* unused */),
      .err_o     (c_intg_err[i_word*2+:2])
    );
    assign c_no_intg_q[i_word*32+:32] = c_intg_q[i_word*39+:32];
  end

  always_ff @(posedge clk_i) begin
    if (c_wr_en) begin
      c_intg_q <= c_intg_d;
    end
  end

  //////////////////
  // Register TMP //
  //////////////////
  logic                           tmp_wr_en;
  logic [ExtQWLEN-1:0]            tmp_intg_d;
  logic [ExtQWLEN-1:0]            tmp_intg_q;
  logic [QWLEN-1:0]               tmp_no_intg_d;
  logic [QWLEN-1:0]               tmp_no_intg_q;
  logic [2*BaseWordsPerQWLEN-1:0] tmp_intg_err;

  for (genvar i_word = 0; i_word < BaseWordsPerQWLEN; i_word++) begin : g_tmp_words
    prim_secded_inv_39_32_enc i_tmp_secded_enc (
      .data_i(tmp_no_intg_d[i_word*32+:32]),
      .data_o(tmp_intg_d[i_word*39+:39])
    );
    prim_secded_inv_39_32_dec i_tmp_secded_dec (
      .data_i    (tmp_intg_q[i_word*39+:39]),
      .data_o    (/* unused because we abort on any integrity error */),
      .syndrome_o(/* unused */),
      .err_o     (tmp_intg_err[i_word*2+:2])
    );
    assign tmp_no_intg_q[i_word*32+:32] = tmp_intg_q[i_word*39+:32];
  end

  always_ff @(posedge clk_i) begin
    if (tmp_wr_en) begin
      tmp_intg_q <= tmp_intg_d;
    end
  end

  ////////////////////
  // Input blanking //
  ////////////////////
  logic [WLEN-1:0] operand_a_blanked;
  logic [WLEN-1:0] operand_b_blanked;

  // SEC_CM: DATA_REG_SW.SCA
  prim_blanker #(.Width(WLEN)) u_operand_a_blanker (
    .in_i (operation_i.operand_a),
    .en_i (predec_i.op_en),
    .out_o(operand_a_blanked)
  );

  // SEC_CM: DATA_REG_SW.SCA
  prim_blanker #(.Width(WLEN)) u_operand_b_blanker (
    .in_i (operation_i.operand_b),
    .en_i (predec_i.op_en),
    .out_o(operand_b_blanked)
  );

  ///////////////////
  // MOD Extractor //
  ///////////////////
  // The modulus and Montgomery constant are expected in the MOD register at:
  // q  @ [31:0]
  // mu @ [63:32]
  logic [2*39-1:0]         ispr_mod_intg_blanked;
  logic [ExtWLEN-2*39-1:0] unused_ispr_mod_intg;
  logic [63:0]             mod_no_intg;
  logic [3:0]              mod_intg_err;

  // Only the first two 32-bit words are required as q and mu reside in the first 64 bits.
  // SEC_CM: DATA_REG_SW.SCA
  prim_blanker #(.Width(2*39)) u_mod_blanker (
    .in_i (ispr_mod_intg_i[2*39-1:0]),
    .en_i (predec_i.is_mod),
    .out_o(ispr_mod_intg_blanked)
  );

  assign unused_ispr_mod_intg = ~ispr_mod_intg_i[ExtWLEN-1:2*39];

  for (genvar i_word = 0; i_word < 2; i_word++) begin : g_mod_words
    prim_secded_inv_39_32_dec i_mod_secded_dec (
      .data_i    (ispr_mod_intg_blanked[i_word*39+:39]),
      .data_o    (/* unused because we abort on any integrity error */),
      .syndrome_o(/* unused */),
      .err_o     (mod_intg_err[i_word*2+:2])
    );
    assign mod_no_intg[i_word*32+:32] = ispr_mod_intg_blanked[i_word*39+:32];
  end

  // For the 32-bit vectorized multiplications we have to replicate the constants
  logic [QWLEN-1:0] mod_q; // The Montgomery modulus q
  logic [QWLEN-1:0] mod_mu; // The Montgomery constant, mu = (-q)^-1 mod 2^ELEN

  assign mod_q  = {2{mod_no_intg[31:0]}};
  assign mod_mu = {2{mod_no_intg[63:32]}};

  ///////////////////////////
  // Vectorized multiplier //
  ///////////////////////////

  // Input operand quad word selection
  logic [1:0]       op_a_qw_sel;
  logic [1:0]       op_b_qw_sel;
  logic [QWLEN-1:0] qword_a;
  logic [QWLEN-1:0] qword_b;
  logic [QWLEN-1:0] qword_b_lane;

  always_comb begin
    unique case (op_a_qw_sel)
      2'd0: qword_a = operand_a_blanked[QWLEN*0+:QWLEN];
      2'd1: qword_a = operand_a_blanked[QWLEN*1+:QWLEN];
      2'd2: qword_a = operand_a_blanked[QWLEN*2+:QWLEN];
      2'd3: qword_a = operand_a_blanked[QWLEN*3+:QWLEN];
      default: qword_a = '0;
    endcase
  end

  // Pick the lane index and replicate
  assign qword_b_lane = {2{operand_b_blanked[predec_i.lane_index*32+:32]}};

  always_comb begin
    qword_b = '0;
    if ((predec_i.mul_type == MacMulVecLane) ||
        (predec_i.mul_type == MacMulVecModLane)) begin
      qword_b = qword_b_lane;
    end else begin
      unique case (op_b_qw_sel)
        2'd0: qword_b = operand_b_blanked[QWLEN*0+:QWLEN];
        2'd1: qword_b = operand_b_blanked[QWLEN*1+:QWLEN];
        2'd2: qword_b = operand_b_blanked[QWLEN*2+:QWLEN];
        2'd3: qword_b = operand_b_blanked[QWLEN*3+:QWLEN];
        default: qword_b = '0;
      endcase
    end
  end

  // Multiplier operand selection
  logic             mul_op_a_tmp_sel;
  mul_op_b_sel_e    mul_op_b_sel;
  logic [QWLEN-1:0] mul_op_a;
  logic [QWLEN-1:0] mul_op_b;
  logic [HWLEN-1:0] mul_res;

  assign mul_op_a = mul_op_a_tmp_sel ? qword_a : tmp_no_intg_q;

  always_comb begin
    unique case (mul_op_b_sel)
      MulOpB:  mul_op_b = qword_b;
      MulOpMu: mul_op_b = mod_mu;
      MulOpq:  mul_op_b = mod_q;
      default: mul_op_b = '0;
    endcase
  end

  otbn_vec_multiplier u_vec_multiplier (
    .operand_a_i(mul_op_a),
    .operand_b_i(mul_op_b),
    .elen_i     (predec_i.elen),
    .result_o   (mul_res)
  );

  //////////////////////////////////////////////////////////
  // Multiplier result handling for vectorized Montgomery //
  //////////////////////////////////////////////////////////
  logic             mul_mod_en;
  logic [HWLEN-1:0] mul_res_mod;
  logic [QWLEN-1:0] tmp_value;

  // This blanker is also used to clear TMP and C.
  // SEC_CM: DATA_REG_SW.SCA
  prim_blanker #(.Width(HWLEN)) u_mul_res_mod_blanker (
    .in_i (mul_res),
    .en_i (mul_mod_en),
    .out_o(mul_res_mod)
  );

  // Store the full result of the multiplication in register C.
  always_comb begin
    c_no_intg_d = '0;
    unique case (1'b1)
      sec_wipe_c_urnd_i: c_no_intg_d = urnd_data_i[HWLEN-1:0];
      default:           c_no_intg_d = mul_res_mod;
    endcase
  end

  // Store only the lower ELEN bits of the parallel multiplications in register TMP.
  assign tmp_value = {mul_res_mod[32*2+:32], mul_res_mod[32*0+:32]};

  always_comb begin
    tmp_no_intg_d = '0;
    unique case (1'b1)
      sec_wipe_tmp_urnd_i: tmp_no_intg_d = urnd_data_i[QWLEN-1:0];
      default:             tmp_no_intg_d = tmp_value;
    endcase
  end

  // Adder operand blanking and extension
  logic             mul_add_en;
  logic [HWLEN-1:0] half_mul_res_add;
  logic [WLEN-1:0]  mul_res_add;

  // SEC_CM: DATA_REG_SW.SCA
  prim_blanker #(.Width(HWLEN)) u_half_mul_res_blanker (
    .in_i (mul_res),
    .en_i (mul_add_en),
    .out_o(half_mul_res_add)
  );

  assign mul_res_add = {{HWLEN{1'b0}}, half_mul_res_add};

  //////////////////////////////////////////////////////////////////////
  // Multiplier result handling for regular vectorized multiplication //
  //////////////////////////////////////////////////////////////////////
  // Truncating and blanking of results towards the ACC merger for vectorized multiplication
  // without modulo reduction.
  logic [QWLEN-1:0] mul_res_merger;

  // SEC_CM: DATA_REG_SW.SCA
  prim_blanker #(.Width(QWLEN)) u_mul_res_merger_blanker (
    .in_i ({mul_res[32*2+:32], mul_res[32*0+:32]}),
    .en_i (predec_i.mul_merger_en),
    .out_o(mul_res_merger)
  );

  ///////////////////////////////////////////////////////////
  // Multiplier result handling for regular multiplication //
  ///////////////////////////////////////////////////////////
  // Blank and shift result prior to accumulation
  logic [HWLEN-1:0] mul_res_pre_shifted;
  logic [WLEN-1:0]  mul_res_shifted;

  // SEC_CM: DATA_REG_SW.SCA
  prim_blanker #(.Width(HWLEN)) u_mul_res_shift_blanker (
    .in_i (mul_res),
    .en_i (predec_i.mul_shift_en),
    .out_o(mul_res_pre_shifted)
  );

  // Shift the QWLEN multiply result into a WLEN word before accumulating using the shift amount
  // supplied in the instruction (pre_acc_shift_imm).
  always_comb begin
    mul_res_shifted = '0;

    unique case (operation_i.pre_acc_shift_imm)
      2'd0: mul_res_shifted = {{QWLEN * 2{1'b0}}, mul_res_pre_shifted};
      2'd1: mul_res_shifted = {{QWLEN{1'b0}}, mul_res_pre_shifted, {QWLEN{1'b0}}};
      2'd2: mul_res_shifted = {mul_res_pre_shifted, {QWLEN * 2{1'b0}}};
      2'd3: mul_res_shifted = {mul_res_pre_shifted[63:0], {QWLEN * 3{1'b0}}};
      default: mul_res_shifted = '0;
    endcase
  end

  `ASSERT_KNOWN_IF(PreAccShiftImmKnown, operation_i.pre_acc_shift_imm, mac_en_i)

  //////////////////////
  // Vectorized Adder //
  //////////////////////
  logic             c_add_en;
  logic [HWLEN-1:0] c_blanked;
  logic [WLEN-1:0]  acc_add_blanked;
  logic [WLEN-1:0]  adder_op_a;
  logic [WLEN-1:0]  adder_op_b;
  logic [WLEN-1:0]  adder_result;

  // SEC_CM: DATA_REG_SW.SCA
  prim_blanker #(.Width(HWLEN)) u_reg_c_blanker (
    .in_i (c_no_intg_q),
    .en_i (c_add_en),
    .out_o(c_blanked)
  );

  // SEC_CM: DATA_REG_SW.SCA
  // acc_add_en is so if .Z set in MULQACC (zero_acc) so accumulator reads as 0
  prim_blanker #(.Width(WLEN)) u_acc_add_blanker (
    .in_i (acc_no_intg_q),
    .en_i (predec_i.acc_add_en),
    .out_o(acc_add_blanked)
  );

  // Perform the additions. The vectorized path only uses the lower 128 bits of the adder.
  // The full 256 bit width is used for bn.mulqacc instructions.
  // Here the MUXs can be implemented with OR gates because input signals are exclusively blanked
  // for the whole duration of an instruction.
  // - c_blanked is only non zero for Montgomery multiplications where mul_res_shifted is unused.
  //   Vice versa mul_res_shifted is only non zero for regular multiplications where c_blanked is
  //   unused.
  // - mul_res_add is only non zero for vectorized multiplications where acc_add_blanked is unused.
  //   Vice versa acc_add_blanked is only non zero for regular multiplications where mul_res_add is
  //   blanked.
  assign adder_op_a = {{128{1'b0}}, c_blanked} | mul_res_shifted;
  assign adder_op_b = mul_res_add              | acc_add_blanked;

  otbn_vec_adder #(
    .LVLEN(WLEN),
    .LVChunkLEN(VChunkLEN)
  ) u_vec_adder (
    .operand_a_i       (adder_op_a),
    .operand_b_i       (adder_op_b),
    .operand_b_invert_i(1'b0), // always add, never subtract
    .carries_in_i      ('0),
    .use_ext_carry_i   (predec_i.adder_carry_sel),
    .sum_o             (adder_result),
    .carries_out_o     (/* unused */)
  );

  /////////////////////////////////////////////
  // Vectorized adder modulo result handling //
  /////////////////////////////////////////////
  logic             add_mod_en;
  logic [QWLEN-1:0] adder_result_mod;
  logic [QWLEN-1:0] montg_r;

  // Montgomery upper bit selection
  // Take only the upper ELEN bits of the addition.
  // The result is "r" of the montgomery algorithm
  assign adder_result_mod = {adder_result[32*3+:32], adder_result[32*1+:32]};

    prim_blanker #(.Width(QWLEN)) u_add_mod_blanker (
    .in_i (adder_result_mod),
    .en_i (add_mod_en),
    .out_o(montg_r)
  );

  // Critical path optimization
  // We do not perform the conditional subtraction in the MAC to shorten the timing path and
  // save area. The conditional subtraction can be performed in one cycle for all four 64b chunks
  // by using bn.addvm with zero as one input.
  logic [QWLEN-1:0] montg_r_cor;
  assign montg_r_cor = montg_r;

  ///////////////////////////////////////////
  // ACC merging for vectorized operations //
  ///////////////////////////////////////////
  logic             acc_merger_en;
  logic [1:0]       acc_qw_sel;
  logic [QWLEN-1:0] acc_new_qw;
  logic [WLEN-1:0]  acc_old;
  logic [WLEN-1:0]  acc_merged;

  // This MUX can be implemented using a regular OR because both inputs are exclusively blanked.
  // The mul_res_merger comes directly from a blanker which is only active (passes data through) if
  // we are performing a regular vectorized multiplication (default or lane). In this case the
  // montg_r_cor is all zero as the signal is blanked with u_add_mod_blanker. During a Montgomery
  // multiplication the montg_r_cor contains the data but mul_res_merger is blanked.
  // These blankers are exclusively used for the whole duration of an instruction.
  assign acc_new_qw = montg_r_cor | mul_res_merger;

  // This blanker is used to zero the ACC register
  prim_blanker #(.Width(WLEN)) u_acc_merger_blanker (
    .in_i (acc_no_intg_q),
    .en_i (acc_merger_en),
    .out_o(acc_old)
  );

  // Place the computed 64-bit chunk at the desired location in the ACC register.
  assign acc_merged[0*QWLEN+:QWLEN] = (acc_qw_sel == 2'd0) ? acc_new_qw : acc_old[0*QWLEN+:QWLEN];
  assign acc_merged[1*QWLEN+:QWLEN] = (acc_qw_sel == 2'd1) ? acc_new_qw : acc_old[1*QWLEN+:QWLEN];
  assign acc_merged[2*QWLEN+:QWLEN] = (acc_qw_sel == 2'd2) ? acc_new_qw : acc_old[2*QWLEN+:QWLEN];
  assign acc_merged[3*QWLEN+:QWLEN] = (acc_qw_sel == 2'd3) ? acc_new_qw : acc_old[3*QWLEN+:QWLEN];

  //////////////////////////////////////////////////////
  // Adder result handling for regular multiplication //
  //////////////////////////////////////////////////////
  logic [WLEN-1:0] adder_result_blanked;
  logic [WLEN-1:0] regular_acc_update_value;

  prim_blanker #(.Width(WLEN)) u_add_res_blanker (
    .in_i (adder_result),
    .en_i (predec_i.add_res_en),
    .out_o(adder_result_blanked)
  );

  assign regular_acc_update_value = operation_i.shift_acc ?
             {{QWLEN*2{1'b0}}, adder_result_blanked[QWLEN*2+:QWLEN*2]} : adder_result_blanked;

  /////////////////
  // Flag update //
  /////////////////
  // Vectorized operation never updates flags
  logic [1:0] adder_result_hw_is_zero;

  // Split zero check between the two halves of the result. This is used for flag setting (see
  // below).
  assign adder_result_hw_is_zero[0] = adder_result_blanked[WLEN/2-1:0] == 'h0;
  assign adder_result_hw_is_zero[1] = adder_result_blanked[WLEN/2+:WLEN/2] == 'h0;

  assign operation_flags_o.L    = adder_result_blanked[0];
  // L is always updated for .WO, and for .SO when writing to the lower half-word
  assign operation_flags_en_o.L = predec_i.is_vec ? 1'b0 :
                                       operation_i.shift_acc ? ~operation_i.wr_hw_sel_upper : 1'b1;

  // For .SO M is taken from the top-bit of shifted out half-word, otherwise it is taken from the
  // top-bit of the full result.
  assign operation_flags_o.M    = operation_i.shift_acc ? adder_result_blanked[WLEN/2-1] :
                                                          adder_result_blanked[WLEN-1];
  // M is always updated for .WO, and for .SO when writing to the upper half-word.
  assign operation_flags_en_o.M = predec_i.is_vec ? 1'b0 :
                                       operation_i.shift_acc ? operation_i.wr_hw_sel_upper : 1'b1;

  // For .SO Z is calculated from the shifted out half-word, otherwise it is calculated on the full
  // result.
  assign operation_flags_o.Z    = operation_i.shift_acc ? adder_result_hw_is_zero[0] :
                                                          &adder_result_hw_is_zero;

  // Z is updated for .WO. For .SO updates are based upon result and half-word:
  // - When writing to lower half-word always update Z.
  // - When writing to upper half-word clear Z if result is non-zero otherwise leave it alone.
  assign operation_flags_en_o.Z = predec_i.is_vec ? 1'b0 :
         operation_i.shift_acc & operation_i.wr_hw_sel_upper ? ~adder_result_hw_is_zero[0] :
                                                               1'b1;

  // MAC never sets the carry flag
  assign operation_flags_o.C    = 1'b0;
  assign operation_flags_en_o.C = 1'b0;

  ////////////////
  // ACC update //
  ////////////////
  always_comb begin
    acc_no_intg_d = '0;
    unique case (1'b1)
      // Non-encoded inputs have to be encoded before writing to the register.
      sec_wipe_acc_urnd_i: begin
        acc_no_intg_d = urnd_data_i;
        acc_intg_d = acc_intg_calc;
      end
      default: begin
        // If performing an ACC ISPR write the next accumulator value is taken from the ISPR write
        // data, otherwise it is drawn from the adder result or the vectorized ACC merger.
        if (ispr_acc_wr_en_i) begin
          acc_intg_d = ispr_acc_wr_data_intg_i;
        end else begin
          // The MUX for the input selection can be implemented with a simple OR gate because both
          // inputs are exclusively blanked. For regular multiplications acc_merged is zero because
          // the ACC merger just receives zero values. For vectorized multiplications (incl.
          // Montgomery) the regular_acc_update_value is zero because add_res_en is reset.
          // These blankers are exclusively used for the whole duration of an instruction.
          acc_no_intg_d = acc_merged | regular_acc_update_value;
          acc_intg_d = acc_intg_calc;
        end
      end
    endcase
  end

  ///////////////////////////
  // Register Write Enable //
  ///////////////////////////
  // The raw write enables are set by the state machine. These are then combined with the input
  // signals which handle the validity of the instruction.
  logic acc_wr_en_raw;
  logic tmp_wr_en_raw;
  logic c_wr_en_raw;

  // Only write to accumulator if the MAC is enabled or an ACC ISPR write is occuring or secure
  // wipe of the internal state is occuring.
  assign acc_wr_en = (acc_wr_en_raw & (mac_en_i & mac_commit_i))
                     | ispr_acc_wr_en_i | sec_wipe_acc_urnd_i;
  assign tmp_wr_en = (tmp_wr_en_raw & (mac_en_i & mac_commit_i)) | sec_wipe_tmp_urnd_i;
  assign c_wr_en   = (c_wr_en_raw & (mac_en_i & mac_commit_i)) | sec_wipe_c_urnd_i;

  /////////////////
  // Control FSM //
  /////////////////
  // Only advance to next state if we have a go. Don't advance if there is an OTBN error (commit
  // is reset in this case).
  logic do_advance;
  assign do_advance = mac_en_i & mac_commit_i;
  logic operation_valid_raw;

  logic expected_mul_shift_en;
  logic expected_mul_merger_en;
  logic expected_add_res_en;

  /**
   * The MAC module implements the following types of MAC:
   * - Regular 64b multiplication with accumulation in ACC
   * - Vectorized Multiplication for 32b elements of a 256b vector (WDR)
   *   - Either elementwise or multiply each element of vector a with a fixed element
   *     of vector b. The later is hereinafter described as Lane multiplication.
   * - Vectorized Multiplication with Montgomery reduction (32b elements)
   *   - Also elementwise or lane mode
   *
   * The different multicycle operations are implemented with a FSM. We always start in
   * the "MacRegular" state. This state however includes also the start state of the four other
   * operations. This is required as the regular multiplication is single cycle. We cycle through
   * all required states where the last state asserts the valid flag. Afterwards we go back to
   * the MacRegular state and prepare for the next operation.
   *
   * Regular multiplication: single cycle, we stay in MacRegular
   * Vectorized: MacRegular -> MacQW1 -> MacQW2 -> MacDoneQW
   * Vectorized Lane: Same as Vectorized but multiplier operator b is fixed
   *
   * Vectorized Montgomery:
   * The Montgomery algorithm is implemented in hardware. It requires 3 cycles to process one
   * quarter word (i.e. 2x 32b elements). Thus the total duration is 12 cycles.
   *     MacRegular -> MacModQW0C1 -> MacModQW0C2 -> ... -> MacModQW3C1 -> MacDoneModQW3C2
   *
   * Vectorized Montgomery with lane:
   * Same as vectorized Montgomery but with fixed operand b selection.
   *
   * Blanking is implemented on the whole datapath. Some control signals are predecoded to reduce
   * SCA leakage. However, some control signals do change depending on the cycle and thus are not
   * predecoded. If required the predecoding could be implemented in this FSM.
   */
  always_comb begin : mac_fsm
    // Default assignments
    mac_state_d = mac_state_q;

    op_a_qw_sel      = 2'd0;
    op_b_qw_sel      = 2'd0;
    acc_qw_sel       = 2'd0;
    mul_op_a_tmp_sel = 1'b1; // select a as it is blanked
    mul_op_b_sel     = MulOpB;
    tmp_wr_en_raw    = 1'b0;
    c_wr_en_raw      = 1'b0;
    acc_wr_en_raw    = 1'b0;

    operation_valid_raw = 1'b0;

    // TODO: These 5 signals definitely must be predecoded
    mul_add_en       = 1'b0;
    mul_mod_en       = 1'b0;
    c_add_en         = 1'b0;
    add_mod_en       = 1'b0;
    acc_merger_en    = 1'b0;

    expected_mul_shift_en  = 1'b0;
    expected_mul_merger_en = 1'b0;
    expected_add_res_en    = 1'b0;

    // TODO: Maybe merge similar cases?
    unique case (mac_state_q)
      MacRegular: begin
        // Includes states MacStartQW0 and MacStartModQW0C0
        unique case (predec_i.mul_type)
          MacMulRegular: begin
            op_a_qw_sel         = operation_i.operand_a_qw_sel;
            op_b_qw_sel         = operation_i.operand_b_qw_sel;
            acc_wr_en_raw       = 1'b1;
            operation_valid_raw = 1'b1;

            // Only expect the blankers to be active if we are enabled
            expected_mul_shift_en  = 1'b1 & mac_en_i;
            expected_add_res_en    = 1'b1 & mac_en_i;
          end
          MacMulVec,
          MacMulVecLane: begin
            op_a_qw_sel   = 2'd0;
            op_b_qw_sel   = 2'd0; // No effect for Lane
            acc_wr_en_raw = 1'b1; // Clear ACC register to zero
            mac_state_d   = MacQW1;

            // Only expect the blankers to be active if we are enabled
            expected_mul_merger_en = 1'b1 & mac_en_i;
          end
          MacMulVecMod,
          MacMulVecModLane: begin
            op_a_qw_sel   = 2'd0;
            op_b_qw_sel   = 2'd0; // No effect for Lane
            tmp_wr_en_raw = 1'b1;
            c_wr_en_raw   = 1'b1;
            mul_mod_en    = 1'b1;
            mac_state_d   = MacModQW0C1;
          end
          default: mac_state_d = MacError;
        endcase
      end
      MacQW1: begin
        op_a_qw_sel   = 2'd1;
        op_b_qw_sel   = 2'd1; // No effect for Lane
        acc_qw_sel    = 2'd1;
        acc_wr_en_raw = 1'b1;
        acc_merger_en = 1'b1;
        mac_state_d   = MacQW2;

        expected_mul_merger_en = 1'b1;
      end
      MacQW2: begin
        op_a_qw_sel   = 2'd2;
        op_b_qw_sel   = 2'd2; // No effect for Lane
        acc_qw_sel    = 2'd2;
        acc_wr_en_raw = 1'b1;
        acc_merger_en = 1'b1;
        mac_state_d   = MacDoneQW;

        expected_mul_merger_en = 1'b1;
      end
      MacDoneQW: begin
        op_a_qw_sel         = 2'd3;
        op_b_qw_sel         = 2'd3; // No effect for Lane
        acc_qw_sel          = 2'd3;
        acc_wr_en_raw       = 1'b1;
        acc_merger_en       = 1'b1;
        operation_valid_raw = 1'b1;
        mac_state_d         = MacRegular;

        expected_mul_merger_en = 1'b1;
      end
      MacModQW0C1: begin
        op_a_qw_sel      = 2'd0;
        op_b_qw_sel      = 2'd0; // No effect for Lane
        mul_op_a_tmp_sel = 1'b0;
        mul_op_b_sel     = MulOpMu;
        tmp_wr_en_raw    = 1'b1;
        mul_mod_en       = 1'b1;
        mac_state_d      = MacModQW0C2;
      end
      MacModQW0C2: begin
        op_a_qw_sel      = 2'd0;
        op_b_qw_sel      = 2'd0; // No effect for Lane
        mul_op_a_tmp_sel = 1'b0;
        mul_op_b_sel     = MulOpq;
        acc_wr_en_raw    = 1'b1;
        mul_add_en       = 1'b1;
        c_add_en         = 1'b1;
        add_mod_en       = 1'b1;
        acc_merger_en    = 1'b0; // Clear ACC
        tmp_wr_en_raw    = 1'b1; // Clear TMP, blanker is disabled
        c_wr_en_raw      = 1'b1; // Clear C, blanker is disabled
        mac_state_d      = MacModQW1C0;
      end
      MacModQW1C0: begin
        op_a_qw_sel   = 2'd1;
        op_b_qw_sel   = 2'd1; // No effect for Lane
        acc_qw_sel    = 2'd1;
        tmp_wr_en_raw = 1'b1;
        c_wr_en_raw   = 1'b1;
        mul_mod_en    = 1'b1;
        mac_state_d   = MacModQW1C1;
      end
      MacModQW1C1: begin
        op_a_qw_sel      = 2'd1;
        op_b_qw_sel      = 2'd1; // No effect for Lane
        mul_op_a_tmp_sel = 1'b0;
        mul_op_b_sel     = MulOpMu;
        acc_qw_sel       = 2'd1;
        tmp_wr_en_raw    = 1'b1;
        mul_mod_en       = 1'b1;
        mac_state_d      = MacModQW1C2;
      end
      MacModQW1C2: begin
        op_a_qw_sel      = 2'd1;
        op_b_qw_sel      = 2'd1; // No effect for Lane
        mul_op_a_tmp_sel = 1'b0;
        mul_op_b_sel     = MulOpq;
        acc_qw_sel       = 2'd1;
        acc_wr_en_raw    = 1'b1;
        mul_add_en       = 1'b1;
        c_add_en         = 1'b1;
        add_mod_en       = 1'b1;
        acc_merger_en    = 1'b1;
        tmp_wr_en_raw    = 1'b1; // Clear TMP, blanker is disabled
        c_wr_en_raw      = 1'b1; // Clear C, blanker is disabled
        mac_state_d      = MacModQW2C0;
      end
      MacModQW2C0: begin
        op_a_qw_sel      = 2'd2;
        op_b_qw_sel      = 2'd2; // No effect for Lane
        acc_qw_sel       = 2'd2;
        tmp_wr_en_raw    = 1'b1;
        c_wr_en_raw      = 1'b1;
        mul_mod_en       = 1'b1;
        mac_state_d      = MacModQW2C1;
      end
      MacModQW2C1: begin
        op_a_qw_sel      = 2'd2;
        op_b_qw_sel      = 2'd2; // No effect for Lane
        mul_op_a_tmp_sel = 1'b0;
        mul_op_b_sel     = MulOpMu;
        acc_qw_sel       = 2'd2;
        tmp_wr_en_raw    = 1'b1;
        mul_mod_en       = 1'b1;
        mac_state_d      = MacModQW2C2;
      end
      MacModQW2C2: begin
        op_a_qw_sel      = 2'd2;
        op_b_qw_sel      = 2'd2; // No effect for Lane
        mul_op_a_tmp_sel = 1'b0;
        mul_op_b_sel     = MulOpq;
        acc_qw_sel       = 2'd2;
        acc_wr_en_raw    = 1'b1;
        mul_add_en       = 1'b1;
        c_add_en         = 1'b1;
        add_mod_en       = 1'b1;
        acc_merger_en    = 1'b1;
        tmp_wr_en_raw    = 1'b1; // Clear TMP, blanker is disabled
        c_wr_en_raw      = 1'b1; // Clear C, blanker is disabled
        mac_state_d      = MacModQW3C0;
      end
      MacModQW3C0: begin
        op_a_qw_sel      = 2'd3;
        op_b_qw_sel      = 2'd3; // No effect for Lane
        acc_qw_sel       = 2'd3;
        tmp_wr_en_raw    = 1'b1;
        c_wr_en_raw      = 1'b1;
        mul_mod_en       = 1'b1;
        mac_state_d      = MacModQW3C1;
      end
      MacModQW3C1: begin
        op_a_qw_sel      = 2'd3;
        op_b_qw_sel      = 2'd3; // No effect for Lane
        mul_op_a_tmp_sel = 1'b0;
        mul_op_b_sel     = MulOpMu;
        acc_qw_sel       = 2'd3;
        tmp_wr_en_raw    = 1'b1;
        mul_mod_en       = 1'b1;
        mac_state_d      = MacDoneModQW3C2;
      end
      MacDoneModQW3C2: begin
        op_a_qw_sel         = 2'd3;
        op_b_qw_sel         = 2'd3; // No effect for Lane
        mul_op_a_tmp_sel    = 1'b0;
        mul_op_b_sel        = MulOpq;
        acc_qw_sel          = 2'd3;
        acc_wr_en_raw       = 1'b1;
        mul_add_en          = 1'b1;
        c_add_en            = 1'b1;
        add_mod_en          = 1'b1;
        acc_merger_en       = 1'b1;
        tmp_wr_en_raw       = 1'b1; // Clear TMP, blanker is disabled
        c_wr_en_raw         = 1'b1; // Clear C, blanker is disabled
        mac_state_d         = MacRegular;
        operation_valid_raw = 1'b1;
      end
      MacError: mac_state_d = MacError; // TODO: trigger alarm
      default: mac_state_d = MacError; // Consider triggering an error or alert in this case.
    endcase
    // Revert assigned state change if we are not allowed to advance except in error case
    if (!do_advance && (mac_state_d != MacError)) begin
      mac_state_d = mac_state_q;
    end
  end

  `PRIM_FLOP_SPARSE_FSM(u_mac_state_regs, mac_state_d, mac_state_q, mac_state_e, MacRegular)

  //////////////////////
  // Result selection //
  //////////////////////
  // Here the output MUX can be replaced with a simple OR gate because both inputs are exclusively
  // blanked. For regular multiplications the acc_merged is zero because the ACC merging just
  // receives zero inputs. For vectorized multiplications (incl. Montgomery) the
  // adder_result_blanked is blanked. These blankers are exclusively used for the whole duration of
  // an instruction.
  assign operation_result_o = acc_merged | adder_result_blanked;
  assign operation_valid_o  = operation_valid_raw & mac_en_i;

  /////////////////////
  // Integrity error //
  /////////////////////
  // Propagate integrity error only if a register is used and MAC is enabled
  logic tmp_used;
  logic c_used;
  logic mod_used;
  logic acc_used;
  // TMP is used if multiplier operand a is set to TMP
  assign tmp_used = mac_en_i && (!mul_op_a_tmp_sel);
  // c is used if its blanker is enabled
  assign c_used = mac_en_i & c_add_en;
  // MOD is used if modulo operation is active
  assign mod_used = mac_en_i && ((predec_i.mul_type == MacMulVecMod) ||
                                 (predec_i.mul_type == MacMulVecModLane));
  // The ACC is used if we do not reset it or require it to merge the current quarter word
  assign acc_used = mac_en_i && (acc_merger_en ||
      ((predec_i.mul_type == MacMulRegular) && ~operation_i.zero_acc));

  assign operation_intg_violation_err_o = (tmp_used & |(tmp_intg_err)) ||
                                          (c_used   & |(c_intg_err))   ||
                                          (mod_used & |(mod_intg_err)) ||
                                          (acc_used & |(acc_intg_err));

  //////////////////////
  // Redundancy check //
  //////////////////////
  // Some expected signals are set by the FSM
  logic                expected_op_en;
  logic                expected_is_vec;
  logic                expected_is_mod;
  mac_mul_type_e       expected_mul_type;
  mac_elen_e           expected_elen;
  logic [NVecProc-1:0] expected_adder_carry_sel;
  logic [2:0]          expected_lane_index;
  logic                expected_acc_add_en;

  // SEC_CM: CTRL.REDUN
  assign expected_op_en           = mac_en_i;
  assign expected_is_vec          = operation_i.is_vec;
  assign expected_is_mod          = operation_i.is_mod;
  assign expected_mul_type        = operation_i.mul_type;
  assign expected_elen            = operation_i.elen;
  assign expected_adder_carry_sel = operation_i.adder_carry_sel;
  assign expected_lane_index      = operation_i.lane_index;
  assign expected_acc_add_en      = ~operation_i.zero_acc & mac_en_i &
                                    (operation_i.mul_type == MacMulRegular);

  assign predec_error_o = |{expected_op_en           != predec_i.op_en,
                            expected_is_vec          != predec_i.is_vec,
                            expected_is_mod          != predec_i.is_mod,
                            expected_mul_type        != predec_i.mul_type,
                            expected_elen            != predec_i.elen,
                            expected_adder_carry_sel != predec_i.adder_carry_sel,
                            expected_lane_index      != predec_i.lane_index,
                            expected_acc_add_en      != predec_i.acc_add_en,
                            expected_mul_shift_en    != predec_i.mul_shift_en,
                            expected_mul_merger_en   != predec_i.mul_merger_en,
                            expected_add_res_en      != predec_i.add_res_en};

  /////////////////////////////////////
  // Register and secure wipe output //
  /////////////////////////////////////
  assign ispr_acc_intg_o = acc_intg_q;

  assign sec_wipe_err_o = (sec_wipe_acc_urnd_i || sec_wipe_tmp_urnd_i || sec_wipe_c_urnd_i) &
                          ~sec_wipe_running_i;

  `ASSERT(NoISPRAccWrAndMacEn, ~(ispr_acc_wr_en_i & mac_en_i))
endmodule
