# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:otbn.bzl", "otbn_binary", "otbn_sim_test")

package(default_visibility = ["//visibility:public"])

# TODO: generate expectations with hw/ip/otbn/dv/otbnsim/test/bn_simd_testvec_gen.py or similar

otbn_sim_test(
    name = "bnaddv_test",
    srcs = [
        "bnaddv_test.s",
    ],
    exp = "bnaddv_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnaddvm_test",
    srcs = [
        "bnaddvm_test.s",
    ],
    exp = "bnaddvm_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnmulv_overwrite_test",
    srcs = [
        "bnmulv_overwrite_test.s",
    ],
    exp = "bnmulv_overwrite_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnmulv_test",
    srcs = [
        "bnmulv_test.s",
    ],
    exp = "bnmulv_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnmulvm_test",
    srcs = [
        "bnmulvm_test.s",
    ],
    exp = "bnmulvm_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnmulvml_test",
    srcs = [
        "bnmulvml_test.s",
    ],
    exp = "bnmulvml_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnpack_test",
    srcs = [
        "bnpack_test.s",
    ],
    exp = "bnpack_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnunpk_test",
    srcs = [
        "bnunpk_test.s",
    ],
    exp = "bnunpk_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnshv_test",
    srcs = [
        "bnshv_test.s",
    ],
    exp = "bnshv_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnsubv_test",
    srcs = [
        "bnsubv_test.s",
    ],
    exp = "bnsubv_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnsubvm_test",
    srcs = [
        "bnsubvm_test.s",
    ],
    exp = "bnsubvm_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bntrn1_test",
    srcs = [
        "bntrn1_test.s",
    ],
    exp = "bntrn1_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bntrn2_test",
    srcs = [
        "bntrn2_test.s",
    ],
    exp = "bntrn2_test.exp",
    deps = [],
)
