# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:otbn.bzl", "otbn_binary", "otbn_sim_test")

package(default_visibility = ["//visibility:public"])

# TODO: generate expectations with hw/ip/otbn/dv/otbnsim/test/bn_simd_testvec_gen.py or similar

otbn_sim_test(
    name = "addv_test",
    srcs = [
        "addv_test.s",
    ],
    exp = "addv_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "addvm_test",
    srcs = [
        "addvm_test.s",
    ],
    exp = "addvm_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnmulv_overwrite_test",
    srcs = [
        "bnmulv_overwrite_test.s",
    ],
    exp = "bnmulv_overwrite_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnmulv_test",
    srcs = [
        "bnmulv_test.s",
    ],
    exp = "bnmulv_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnmulvm_test",
    srcs = [
        "bnmulvm_test.s",
    ],
    exp = "bnmulvm_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnmulvml_test",
    srcs = [
        "bnmulvml_test.s",
    ],
    exp = "bnmulvml_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnpack_test",
    srcs = [
        "bnpack_test.s",
    ],
    exp = "bnpack_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "bnunpk_test",
    srcs = [
        "bnunpk_test.s",
    ],
    exp = "bnunpk_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "shv_test",
    srcs = [
        "shv_test.s",
    ],
    exp = "shv_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "subv_test",
    srcs = [
        "subv_test.s",
    ],
    exp = "subv_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "subvm_test",
    srcs = [
        "subvm_test.s",
    ],
    exp = "subvm_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "trn1_test",
    srcs = [
        "trn1_test.s",
    ],
    exp = "trn1_test.exp",
    deps = [],
)

otbn_sim_test(
    name = "trn2_test",
    srcs = [
        "trn2_test.s",
    ],
    exp = "trn2_test.exp",
    deps = [],
)
